lab:
  description: ''
  notes: ''
  timestamp: 1589982399.9665384
  title: 6.1.2 Lab - Investigate Static Routes
  version: 0.0.3
nodes:
  - id: n0
    label: R1
    node_definition: iosv
    x: -450
    y: 50
    configuration: |-
      hostname R1
      no ip domain lookup
      ipv6 unicast-routing
      banner motd # R1, Investigate Static Routes #
      line con 0
       exec-timeout 0 0
       logging synchronous
       exit
      line vty 0 4
       privilege level 15
       password cisco123
       exec-timeout 0 0
       logging synchronous
       login
       exit
      interface g0/0
       ip address 10.1.2.1 255.255.255.0
       ipv6 address fe80::1:1 link-local
       ipv6 address 2001:db8:acad:1012::1/64
       no shutdown
       exit
      interface g0/2
       ip address 10.1.3.1 255.255.255.128
       ipv6 address fe80::1:2 link-local
       ipv6 address 2001:db8:acad:1013::1/64
       no shutdown
       exit
      interface g0/3
       ip address 10.1.3.129 255.255.255.128
       ipv6 address fe80::1:3 link-local
       ipv6 address 2001:db8:acad:1014::1/64
       no shutdown
       exit
      interface loopback 0
       ip address 192.168.1.1 255.255.255.224
       ipv6 address fe80::1:4 link-local
       ipv6 address 2001:db8:acad:1000::1/64
       no shutdown
       exit
      end
    image_definition: iosv-158-3
    tags: []
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        slot: 0
        label: GigabitEthernet0/0
        type: physical
      - id: i2
        slot: 1
        label: GigabitEthernet0/1
        type: physical
      - id: i3
        slot: 2
        label: GigabitEthernet0/2
        type: physical
      - id: i4
        slot: 3
        label: GigabitEthernet0/3
        type: physical
  - id: n1
    label: R2
    node_definition: iosv
    x: -350
    y: -100
    configuration: |-
      hostname R2
      no ip domain lookup
      ipv6 unicast-routing
      banner motd # R2, Investigate Static Routes #
      line con 0
       exec-timeout 0 0
       logging synchronous
       exit
      line vty 0 4
       privilege level 15
       password cisco123
       exec-timeout 0 0
       logging synchronous
       login
       exit
      interface g0/0
       ip address 10.1.2.2 255.255.255.0
       ipv6 address fe80::2:1 link-local
       ipv6 address 2001:db8:acad:1012::2/64
       no shutdown
       exit
      interface g0/1
       ip address 10.2.3.2 255.255.255.0
       ipv6 address fe80::2:2 link-local
       ipv6 address 2001:db8:acad:1023::2/64
       no shutdown
       exit
      interface loopback 0
       ip address 192.168.2.1 255.255.255.224
       ipv6 address fe80::2:3 link-local
       ipv6 address 2001:db8:acad:2000::1/64
       no shutdown
       exit
      end
    image_definition: iosv-158-3
    tags: []
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        slot: 0
        label: GigabitEthernet0/0
        type: physical
      - id: i2
        slot: 1
        label: GigabitEthernet0/1
        type: physical
      - id: i3
        slot: 2
        label: GigabitEthernet0/2
        type: physical
      - id: i4
        slot: 3
        label: GigabitEthernet0/3
        type: physical
  - id: n2
    label: R3
    node_definition: iosv
    x: -200
    y: 50
    configuration: |-
      hostname R3
      no ip domain lookup
      ipv6 unicast-routing
      banner motd # R3, Investigate Static Routes #
      line con 0
       exec-timeout 0 0
       logging synchronous
       exit
      line vty 0 4
       privilege level 15
       password cisco123
       exec-timeout 0 0
       logging synchronous
       login
       exit
      interface g0/0
       ip address 10.2.3.3 255.255.255.0
       ipv6 address fe80::3:1 link-local
       ipv6 address 2001:db8:acad:1023::3/64
       no shutdown
       exit
      interface g0/2
       ip address 10.1.3.3 255.255.255.128
       ipv6 address fe80::3:2 link-local
       ipv6 address 2001:db8:acad:1013::3/64
       no shutdown
       exit
      interface g0/3
       ip address 10.1.3.130 255.255.255.128
       ipv6 address fe80::3:3 link-local
       ipv6 address 2001:db8:acad:1014::3/64
       no shutdown
       exit
      interface loopback 0
       ip address 192.168.3.1 255.255.255.224
       ipv6 address fe80::3:4 link-local
       ipv6 address 2001:db8:acad:3000::1/64
       no shutdown
       exit
      end
    image_definition: iosv-158-3
    tags: []
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        slot: 0
        label: GigabitEthernet0/0
        type: physical
      - id: i2
        slot: 1
        label: GigabitEthernet0/1
        type: physical
      - id: i3
        slot: 2
        label: GigabitEthernet0/2
        type: physical
      - id: i4
        slot: 3
        label: GigabitEthernet0/3
        type: physical
links:
  - id: l0
    i1: i1
    n1: n0
    i2: i1
    n2: n1
  - id: l1
    i1: i2
    n1: n1
    i2: i1
    n2: n2
  - id: l2
    i1: i3
    n1: n0
    i2: i3
    n2: n2
  - id: l3
    i1: i4
    n1: n0
    i2: i4
    n2: n2
